import type { AdminPermission, ControlLayer } from './admin-permissions';

export type EndpointPolicy = {
  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  path: string;
  permission: AdminPermission;
  layer: ControlLayer;
};

export const ADMIN_ENDPOINT_POLICY_REGISTRY: readonly EndpointPolicy[] = [
  { method: 'POST', path: '/api/v1/auth/admin/mfa/setup/start', permission: 'users:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/auth/admin/mfa/setup/confirm', permission: 'users:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/auth/admin/mfa/disable', permission: 'users:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/invites', permission: 'ops:write', layer: 'C' },
  { method: 'POST', path: '/api/v1/admin/invites/cleanup-expired', permission: 'ops:write', layer: 'C' },
  { method: 'GET', path: '/api/v1/admin/analytics/revenue', permission: 'analytics:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/analytics/outbox-dead-letter/:id/replay-preview', permission: 'analytics:replay', layer: 'B' },
  { method: 'POST', path: '/api/v1/admin/analytics/outbox-dead-letter/:id/replay', permission: 'analytics:replay', layer: 'B' },
  { method: 'GET', path: '/api/v1/admin/analytics/outbox-dead-letter', permission: 'analytics:replay', layer: 'B' },
  { method: 'GET', path: '/api/v1/admin/analytics/inbox-failures', permission: 'analytics:replay', layer: 'B' },
  { method: 'POST', path: '/api/v1/admin/analytics/inbox-failures/:id/replay-preview', permission: 'analytics:replay', layer: 'B' },
  { method: 'POST', path: '/api/v1/admin/analytics/inbox-failures/:id/replay', permission: 'analytics:replay', layer: 'B' },
  { method: 'GET', path: '/api/v1/admin/analytics/revenue/export', permission: 'analytics:export', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/analytics/funnel', permission: 'analytics:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/analytics/inventory-alerts', permission: 'analytics:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/analytics/notifications', permission: 'analytics:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/analytics/reconciliation-issues', permission: 'analytics:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/analytics/category-breakdown', permission: 'analytics:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/coupons/analytics', permission: 'coupons:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/coupons', permission: 'coupons:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/coupons', permission: 'coupons:write', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/coupons/:id', permission: 'coupons:write', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/coupons/:id/status', permission: 'coupons:write', layer: 'A' },
  { method: 'DELETE', path: '/api/v1/admin/coupons/:id', permission: 'coupons:write', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/coupons/:id/restore', permission: 'coupons:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/coupons/:id/audit', permission: 'coupons:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/dashboard/kpis', permission: 'dashboard:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/dashboard/sales-chart', permission: 'dashboard:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/dashboard/top-products', permission: 'dashboard:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/inventory', permission: 'inventory:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/inventory/low-stock', permission: 'inventory:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/inventory/:variantId', permission: 'inventory:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/orders', permission: 'orders:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/orders/board', permission: 'orders:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/orders/export', permission: 'orders:export', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/orders/:id', permission: 'orders:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/orders/:id/invoice.pdf', permission: 'orders:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/status', permission: 'orders:write', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/orders/:id/ship', permission: 'orders:write', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/orders/:id/schedule-pickup', permission: 'orders:write', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/orders/:id/print-label', permission: 'orders:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/orders/:id/cancel', permission: 'orders:refund', layer: 'B' },
  { method: 'POST', path: '/api/v1/admin/orders/:id/notifications/retrigger', permission: 'orders:notify', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/return-requests', permission: 'orders:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/return-requests/:id', permission: 'orders:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/products', permission: 'products:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/products/:id', permission: 'products:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/products/import-csv', permission: 'products:write', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/products', permission: 'products:write', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/products/:id/variants/:variantId', permission: 'products:write', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/products/:id/variants', permission: 'products:write', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/products/:id', permission: 'products:write', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/products/:id/images', permission: 'products:write', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/products/:id/images/reorder', permission: 'products:write', layer: 'A' },
  { method: 'DELETE', path: '/api/v1/admin/products/:id/images/:imageId', permission: 'products:write', layer: 'A' },
  { method: 'DELETE', path: '/api/v1/admin/products/:id', permission: 'products:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/categories', permission: 'categories:read', layer: 'A' },
  { method: 'POST', path: '/api/v1/admin/categories', permission: 'categories:write', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/categories/:id', permission: 'categories:write', layer: 'A' },
  { method: 'DELETE', path: '/api/v1/admin/categories/:id', permission: 'categories:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/queues', permission: 'queues:inspect', layer: 'C' },
  { method: 'GET', path: '/api/v1/admin/queues/dlq/summary', permission: 'queues:inspect', layer: 'C' },
  { method: 'GET', path: '/api/v1/admin/reviews', permission: 'reviews:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/reviews/:id/moderate', permission: 'reviews:moderate', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/settings/shipping', permission: 'settings:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/settings/shipping', permission: 'settings:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/settings/store', permission: 'settings:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/settings/store', permission: 'settings:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/settings/notifications', permission: 'settings:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/settings/notifications', permission: 'settings:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/settings/inventory', permission: 'settings:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/settings/inventory', permission: 'settings:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/settings/cod', permission: 'settings:read', layer: 'A' },
  { method: 'PATCH', path: '/api/v1/admin/settings/cod', permission: 'settings:write', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/users', permission: 'users:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/admin/users/:id', permission: 'users:read', layer: 'A' },
  { method: 'GET', path: '/api/v1/ops/session', permission: 'ops:read', layer: 'C' },
  { method: 'GET', path: '/api/v1/ops/load-shed', permission: 'ops:read', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/load-shed', permission: 'ops:write', layer: 'C' },
  { method: 'GET', path: '/api/v1/ops/config/overview', permission: 'ops:read', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/config/validate', permission: 'ops:write', layer: 'C' },
  { method: 'GET', path: '/api/v1/ops/config/stored', permission: 'ops:read', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/config/save', permission: 'ops:write', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/otp/request', permission: 'ops:write', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/otp/verify', permission: 'ops:write', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/invites', permission: 'ops:approve', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/invites/cleanup-expired', permission: 'ops:approve', layer: 'C' },
  { method: 'GET', path: '/api/v1/ops/approvals', permission: 'ops:read', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/approvals/:requestId/confirm', permission: 'ops:approve', layer: 'C' },
  { method: 'POST', path: '/api/v1/ops/approvals/:requestId/reject', permission: 'ops:approve', layer: 'C' },
  { method: 'GET', path: '/api/v1/ops/audit/logs', permission: 'ops:read', layer: 'C' }
];
